import type { StoryScript } from "../../contracts/story-script.types.ts";

export type GenerateRemotionSceneInput = {
  storyScript: StoryScript;
};

export const generateRemotionScene = ({
  storyScript,
}: GenerateRemotionSceneInput): string => {
  const timelineLiteral = JSON.stringify(storyScript.timeline, null, 2);
  const subtitlesLiteral = JSON.stringify(storyScript.subtitles, null, 2);

  return `// Generated by LihuaCat AI code mode
export const videoConfig = ${JSON.stringify(storyScript.video, null, 2)};

export const timeline = ${timelineLiteral};
export const subtitles = ${subtitlesLiteral};

export const renderScene = () => {
  return {
    mode: "ai_code",
    frameRate: videoConfig.fps,
    durationSec: videoConfig.durationSec,
    sceneCount: timeline.length,
    subtitleCount: subtitles.length
  };
};
`;
};
